// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyChI16X9grBgj1KLJPpE5Kb1mFwfN4vvkg',
    appId: '1:248775915995:web:82f6b4c3fcfdfa537c4ffe',
    messagingSenderId: '248775915995',
    projectId: 'carszivo-3f88f',
    authDomain: 'carszivo-3f88f.firebaseapp.com',
    storageBucket: 'carszivo-3f88f.firebasestorage.app',
    measurementId: 'G-221ZKX05XE',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDdk1IQspSHzGpQ9Npm-tm9dtQq_RPPvn8',
    appId: '1:248775915995:android:5d9d95838775283a7c4ffe',
    messagingSenderId: '248775915995',
    projectId: 'carszivo-3f88f',
    storageBucket: 'carszivo-3f88f.firebasestorage.app',
  );
}
