name: Flutter Web CI

on:
  push:
    branches: [ main ]

  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: mobile_app

    steps:
      - uses: actions/checkout@v4
        with:
          submodules: false

      - uses: subosito/flutter-action@v2
        with:
          flutter-version: "3.35.0"

      - run: flutter --version
      - run: flutter pub get
      - run: flutter analyze
      - run: flutter build web
